# Generated by Django 3.0.2 on 2020-07-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewClasses',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.FloatField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=40)),
                ('contact', models.IntegerField(default=None, unique=True)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('passw', models.CharField(max_length=40)),
            ],
        ),
    ]
